version: 0.2

env:
  variables:
    # テスト対象のアプリケーションURL（デプロイ後のURL）
    TARGET_URL: "https://todolist-sample.com"
    # Playwrightの設定
    PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"
  secrets-manager:
    # 必要に応じて認証情報などを追加

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 18
    commands:
      - echo "Installing test dependencies"
      - pip install --user pytest pytest-html locust coverage jinja2
      - export PATH=$PATH:$HOME/.local/bin
      
      # Playwrightの依存関係をインストール
      # 注: mcr.microsoft.com/playwright:v1.51.0-nobleイメージを使用する場合、
      # 必要なブラウザと依存関係はすでにインストールされています
      - echo "Setting up Playwright"
      - npm install -g playwright@latest

  pre_build:
    commands:
      - echo "Test preparation started on `date`"
      - echo "Checking connectivity to target application"
      - curl -s -o /dev/null -w "%{http_code}" $TARGET_URL || echo "Warning: Target application may not be available"

  build:
    commands:
      - echo "Tests started on `date`"
      
      # 負荷テスト（パフォーマンステスト）の実行
      - echo "Running performance tests"
      - locust -f tests/performance/locustfile.py --headless -u 10 -r 2 -t 1m --html=performance_report.html --host=$TARGET_URL || true
      - echo "Performance tests completed"
      
      # E2Eテスト（Playwright）の実行
      - echo "Running E2E tests with Playwright"
      # 以下はテストチームの実装を待つためのプレースホルダー
      # 実際のテスト実行コマンドはテストチームの実装に合わせて変更する
      - mkdir -p playwright-results
      - echo "// プレースホルダー：テストチームが実装したテストを実行する" > placeholder_test.js
      - npx playwright test placeholder_test.js --reporter=html --output=playwright-results || true
      - echo "E2E tests completed"

  post_build:
    commands:
      - echo "Tests completed on `date`"
      - echo "Generating test summary"
      
      # S3バケットにレポートをアップロード
      - aws s3 cp performance_report.html s3://$REPORT_S3_BUCKET/performance/performance_report_$(date +%Y-%m-%d_%H-%M-%S).html || true
      - aws s3 cp --recursive playwright-results s3://$REPORT_S3_BUCKET/e2e/playwright_report_$(date +%Y-%m-%d_%H-%M-%S)/ || true
      - echo "Test reports uploaded to S3"

reports:
  performance-reports:
    files:
      - performance_report.html
    file-format: HTML
    base-directory: .
  e2e-reports:
    files:
      - playwright-results/index.html
    file-format: HTML
    base-directory: .

artifacts:
  files:
    - performance_report.html
    - playwright-results/**/*
    # 必要に応じて他のレポートファイルも追加
  discard-paths: yes
