openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: Created
  /todos/{id}:
    put:
      summary: Update a todo by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: The todo ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete a todo by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: The todo ID
      responses:
        '204':
          description: Deleted
  /register:
    post:
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
  /login:
    post:
      summary: Login a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: OK
  /logout:
    post:
      summary: Logout a user
      responses:
        '200':
          description: OK
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        task:
          type: string
        created_at:
          type: string
          format: date-time
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    Login:
      type: object
      properties:
        identifier:
          type: string
        password:
          type: string
